const express = require("express");
const controller = require("./controller");
const route = express.Router();
route.post("/signup", controller.addUser);
route.post("/product", controller.addProduct);
route.delete("/product/:productId", controller.deleteProduct);
route.post("/cart", controller.addCart);
route.post("/order/:userName", controller.addOrder);
route.get("/login", controller.getUser);
route.get("/tablets", controller.getTablets);
route.get("/mobiles", controller.getMobiles);
route.get("/cart/:userName", controller.getCart);
route.put("/cart/:userName", controller.putCart);
module.exports = route;
